version: '3'
services:
  rabbitmq:
    image: rabbitmq:4.0.5-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - rabbit_data:/var/lib/rabbitmq/
        - rabbit_data:/var/log/rabbitmq/